=pod

=encoding utf8

=head1 ИМѦ

SlovoXCompose

=head1 БЕЛѢЖКА

Правописът и словникът, използвани в този файл са просто пример за употрѣба
на старите букви и не се твърди, че се спазват каквито и да е правила, макар
да отразяват до някаква степен (само)мнението на пишещия.

=head1 ОПИСАНѤ

Това хранилище съдържа файл C<.XCompose> с настройки за съставно въвѣжданѣ на
стари български бꙋкви на Юниѯ-подобни ꙋрѣдби с Ѯ-сървър. Такива изчслителни
ꙋредби сѫ всиччки изданиꙗ на Линуѯ, Фрий-БСД, НЕТ-БСД… Това е възможно
най-леснo осѫществимѭт начин да започнетѣ да въвѣждатѣ бꙋкви ѿ старата ни
азбꙋка. Разбира сѧ, би било добрѣ да има и по-добър, по-бърз начин. Има, но
той все още не сѫществува (в представителен вид). Ако имахме утвърдена
клавиатурна подредба, то това би било този по-добър начин. Уверꙗвѫ ви, че
вече една скѹпина съмишленици работи по въпроса, макар да е само умствено
засѣга.

Прѣдимството на тук прѣдложенѭ начин е в това, че можетѣ лѣсно да добавитѣ
нови собствени послѣдователности ѿ знаци, които при въвѣжданѣ да сѧ
изобразꙗватъ на екранѫ и в документитѣ ви, както и че лесно можете да се
досетите каква би била последователността от знаци, която трѣбва да въвѣдетѣ,
за да се изобрази определен знак. Този начин е добър при спорадично въвѣжданѣ
на стари бꙋкви. Ако сѧ занимаватѣ с такива писаниꙗ като занаꙗтчꙗ, то може би е
по-добре да ползуватѣ клавꙗтурна подредба – звꙋкова или по БДС.

=head1 ꙊКАЗАНꙖ

=head2 Какъ рабѿи C<.XCompose>?

В Юниѯ-подобнитѣ ситеми сѧ ползуват най-чѧсто двѣ изобразꙗващи работни срѣди – KDE или
GNOME. Тези срѣди използуват свои собствени книговни за изобразꙗване на
прозорци, копчета и други видими нагодѣ. Общо вꙁето тези дветѣ (Qt и GTK+)
книговни сѫ най-използуванитѣ и сѧ използуватъ и ѿ други рабѿни среди като
XFCE, LXQT, LXDE, както и ѿ всѣко по-важно приложенѥ.

За да използуват този файл програмите, изобразꙗващи тваритѣ си с помощта на
гореупомѣнатитѣ две книговни, първо трѣбва да сѧ присвои една опрѣдѣлена
стойност на две промѣнливи на обкръженѥто ето така:

    export GTK_IM_MODULE="gtk-im-context-simple"
    export QT_IM_MODULE="gtk-im-context-simple"

Поставетѣ горнитѣ двѣ опрѣдѣленꙗ въ файла C<~/.profile>. Така винаги, когато
влизатѣ въ вашата рабѿнa срѣда, тези промѣнливи ще ꙋказват на приложенꙗта да
зарѣждат файла C<~/.XCompose> или ꙋказанѭ файл въ стойността на промѣнливата на
обкрѫженѥто C<$XCOMPOSEFILE>. 

Сиреч, можетѣ или просто да поставитѣ този C<.XCompose> в домашната си папка,
или въ C<~/.profile> да добавитѣ и слѣднѭ рѣд (примѣр):

    export XCOMPOSEFILE="$HOME/opt/dev/SlovoXCompose/.XCompose"

Замѣстетѣ пѫтѭ до файлѫ според това кѫдѣ се намира на вашата машина.
Това е. Излѣзтѣ и влѣзтѣ ѿново в рабѿната си срѣда, за да сѧ задействат промѣнитѣ.


=head2 Как да въвѣждѫ старитѣ бꙋкви?

Преди да можетѣ да въвѣждатѣ стари бꙋкви само с помощта на клавꙗтурата, е
необходимо да зададетѣ/ꙋкажетѣ/настроитѣ вашиѭ съставен клавиш (Compose key).
На съвремѩните клавиатури нѣма такъв клавиш, така че трѣбва да си изберетѣ
нѣкой рѣдко използуван за други цели клавиш и да настроитѣ него. Въ файлѫ
C</usr/share/X11/xkb/rules/xorg.lst> има пълен списък с възможнитѣ клавиши.
Ето го.


  Compose key          Position of Compose key
  (Съставен)           (Мѣстоположенѥ на съставнѭ ключ)
  compose:ralt         Right Alt
  compose:lwin         Left Win
  compose:lwin-altgr   3rd level of Left Win
  compose:rwin         Right Win
  compose:rwin-altgr   3rd level of Right Win
  compose:menu         Menu
  compose:menu-altgr   3rd level of Menu
  compose:lctrl        Left Ctrl
  compose:lctrl-altgr  3rd level of Left Ctrl
  compose:rctrl        Right Ctrl
  compose:rctrl-altgr  3rd level of Right Ctrl
  compose:caps         Caps Lock
  compose:caps-altgr   3rd level of Caps Lock
  compose:102          &lt;Less/Greater&gt;
  compose:102-altgr    3rd level of &lt;Less/Greater&gt;
  compose:paus         Pause
  compose:prsc         PrtSc
  compose:sclk         Scroll Lock

Този списък може да сѧ види в графичните настройки за клавиатурата
в KDE, GNOME, XFCE...

=begin html

<img src="img/kompose_key_2019-05-05_20-56-42.png" width="800">

=end html


Допълнително (в настройкитѣ за трето ниво):
  lv3:ralt_switch_multikey Right Alt; Shift+Right Alt as Compose

XFCE нѣма отделни настройки за трето ниво, но тази стойност може да се зададе
чрѣз т.нар. „Редактор на настройкитѣ“.

=begin html

<img src="img/ralt_switch_multikey.png" width="800">

=end html

Така в XFCE можетѣ хем да зададете съставен ключ, хем да зададетѣ клавиш
(ключ) за трето ниво.

=head1

ПРИНОС

Можете да помогнете като добавитѣ нови последователности ѿ клавиши или като
поправите неработещите вѣчѣ сѫществуващи такива. Новата последователност ще
заработи слѣд като спрете и пуснете приложенѥто, в което въвѣждатѣ, ѿново.

=head1

СЪСТАВИЛ ТОВА РЪКОВОДСТВО

Красимир Беров

=head1

СЪСТАВИЛИ .XCompose

Красимир Беров


=cut

